global:
  database_dir: "./tasks/"
  export_dir: "./exports/"
  retry_count: 8

dispatch:
  input_dir: "./videos/"
  fps: 8
  width: 512
  height: 288
  max_keypoints: 8000
  depth_confidence: 0.95
  width_confidence: 0.99
  init_frame_width: 512
  init_frame_height: 288
  init_focal_length: 300.0
  highres_width: 1280
  highres_height: 720
  ransac_threshold: 0.200
  max_depth: 10.0
  voxel_downsample: 0.00025
  kernel_radius: 0.0001
