services:
  task:
    image: grounded-sam-2:2605
    build:
      context: .
    volumes:
      - /tmp/grounded-sam-2:/grounded-sam-2/data:rw
      - ./code:/grounded-sam-2/code:rw
    runtime: nvidia
    environment:
      - TEXT_PROMPT
    command: >
      /bin/bash -c "echo START &&
      cp code/main.py . &&
      python3 main.py &&
      chown -R ${UID:-1000}:${GID:-1000} data"
