services:
  task:
    image: colmap-cuda:2605
    build:
      context: .
    volumes:
      - /tmp/colmap-cuda:/colmap/data:rw
    runtime: nvidia
    command: >
      /bin/bash -c "echo START &&
      colmap patch_match_stereo --workspace_path data &&
      colmap stereo_fusion --workspace_path data --output_path data/fused.ply &&
      colmap delaunay_mesher --input_path data --output_path data/meshed-delaunay.ply &&
      chown -R ${UID:-1000}:${GID:-1000} data"
